default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: cashback
  password: cashback


development:
  <<: *default
  database: cashback/development
  host: localhost

test:
  <<: *default
  database: cashback/test
  host: localhost

production:
  <<: *default
  database: cashback/production
  username: cashback
  password: <%= ENV['CASHBACK_DATABASE_PASSWORD'] %>
