default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: cashback
  password: cashback


development:
  <<: *default
  database: cashback_development
  host: db

test:
  <<: *default
  database: cashback_test
  host: db

production:
  <<: *default
  database: cashback_production
  username: cashback
  password: <%= ENV['CASHBACK_DATABASE_PASSWORD'] %>
