default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: cashback
  password: <%= ENV['CASHBACK_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: cashback/development

test:
  <<: *default
  database: cashback/test

production:
  <<: *default
  database: cashback/production
